# Generated by Django 4.0.6 on 2022-07-21 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_phone_best_selling_phone_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='best_selling',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='latest',
            field=models.BooleanField(),
        ),
    ]
